title: Arjunan Yohith
logo: assests/img/headshot_circle.png
description: My name is Arjunan Yohith, and I am currently a Year 2 student pursuing a Diploma in Data Science at Ngee Ann Polytechnic. In my free time, I enjoy socializing with friends and expanding my knowledge through self-learning. I am proficient in applications such as Microsoft Word, PowerPoint, and Power BI, and I excel in working collaboratively within teams.
show_downloads: true
theme: jekyll-theme-minimal
